#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'tf-broadcaster','console_scripts','turtle_obstacle_marker'
__requires__ = 'tf-broadcaster'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('tf-broadcaster', 'console_scripts', 'turtle_obstacle_marker')()
    )
