#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'simple-car-tf','console_scripts','move_car'
__requires__ = 'simple-car-tf'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('simple-car-tf', 'console_scripts', 'move_car')()
    )
